# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('in_future', models.BooleanField(default=False)),
                ('in_future_reason', models.TextField(blank=True)),
                ('is_success', models.BooleanField(default=False)),
                ('by_time', models.CharField(choices=[('TD', 'На сегодня'), ('SH', 'Краткосрочные'), ('MD', 'Среднесрочные'), ('LG', 'Долгострочные')], max_length=2)),
                ('by_type', models.CharField(choices=[('R', 'На результат'), ('P', 'На процесс')], max_length=1)),
                ('why_important', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goal_app.Category')),
            ],
        ),
    ]
