# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_app', '0004_auto_20170424_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='refs_in_control',
            field=models.ManyToManyField(blank=True, null=True, related_name='_goal_refs_in_control_+', to='goal_app.Goal'),
        ),
    ]
