# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_app', '0005_auto_20170424_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
