# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_app', '0006_category_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['priority']},
        ),
        migrations.AddField(
            model_name='goal',
            name='is_personal',
            field=models.BooleanField(default=False),
        ),
    ]
